= git-lfs-clone(1)

== NAME

git-lfs-clone - Efficiently clone a LFS-enabled repository (prior to Git v2.15)

== SYNOPSIS

`git lfs clone` [`git clone` options] <repository> [<directory>]

== DESCRIPTION

This command is deprecated; use `git clone` instead unless you are using
a version of Git earlier than v2.15.0.

Git's support for long-running filter processes was introduced in Git
v2.11.0 and was enhanced with the ability for a filter process such as
Git LFS to delay its processing of individual files so as to allow it to
operate asynchronously.  With these two features, the `git clone` command
will clone an LFS-enabled repository more efficiently than `git lfs clone`,
and so `git clone` should now be preferred in all cases.

However, with versions of Git earlier than v2.15, and especially with
versions earlier than v2.11, the `git lfs clone` command will be more
efficient because it performs `git clone` with Git LFS disabled and then
executes `git lfs pull` directly afterwards.  The batch mode and parallel
downloads performed by `git lfs pull` will be faster than a regular
`git clone` with Git LFS enabled because the older versions of Git will
either invoke Git LFS's "smudge" filter process individually for each
file (prior to v2.11) or will wait for the long-running Git LFS filter
process to operate on each file sequentially rather than in parallel.

The `git lfs clone` command also installs all of the repo-level hooks
(`.git/hooks`) that LFS requires to operate.  If `--separate-git-dir`
is given, the hooks will be installed there.

The `git lfs clone` command is no longer updated to provide parity with
the `git clone` command's options, and may be removed in a future
Git LFS major release.

== OPTIONS

Most options supported by `git clone` as of Git v2.11, plus:

`-I <paths>`::
`--include=<paths>`::
  See <<_include_and_exclude>>.
`-X <paths>`::
`--exclude=<paths>`::
  See <<_include_and_exclude>>.
`--skip-repo`::
  Skip installing repo-level hooks (`.git/hooks`) that LFS
  requires. Disabled by default.

== INCLUDE AND EXCLUDE

You can configure Git LFS to only fetch objects to satisfy references in
certain paths of the repo, and/or to exclude certain paths of the repo,
to reduce the time you spend downloading things you do not use.

In your Git configuration or in a `.lfsconfig` file, you may set either
or both of `lfs.fetchInclude` and `lfs.fetchExclude` to comma-separated
lists of paths. If `lfs.fetchInclude` is defined, Git LFS objects will
only be fetched if their path matches one in that list, and if
`lfs.fetchExclude` is defined, Git LFS objects will only be fetched if
their path does not match one in that list. Paths are matched using
wildcard matching as per gitignore(5).

Note that using the command-line options `-I` and `-X` override the
respective configuration settings. Setting either option to an empty
string clears the value.

== SEE ALSO

git-clone(1), git-lfs-pull(1), gitignore(5).

Part of the git-lfs(1) suite.
