= git-lfs-pre-push(1)

== NAME

git-lfs-pre-push - Git pre-push hook implementation

== SYNOPSIS

[source,console,subs="verbatim,quotes",role=synopsis]
----
*git lfs pre-push* <remote>
----

== DESCRIPTION

Responds to Git pre-hook events. It reads the range of commits from
STDIN, in the following format:

....
<local-ref> SP <local-sha1> SP <remote-ref> SP <remote-sha1> LF
....

If any of those Git objects are associated with Git LFS objects, those
objects will be pushed to the Git LFS API associated with the
destination identified by `<remote>`.

In the case of pushing a new branch, the list of Git objects will be all
of the Git objects in this branch.

In the case of deleting a branch, no attempts to push Git LFS objects
will be made.

When Git invokes a pre-push hook it passes two parameters, only the
first of which is required by the `git lfs pre-push` command.

The `<remote>` argument is expected to contain either the name of the
destination remote or, if a named remote was not specified for the push,
the URL of the destination remote.

Git also always passes the destination remote's URL as a second parameter,
but the `git lfs pre-push` command ignores this additional argument.

== OPTIONS

`-d`::
`--dry-run`::
  Print the files that would be pushed, without actually pushing them.
`GIT_LFS_SKIP_PUSH`::
   Do nothing on pre-push. For more information, see git-lfs-config(5).

== SEE ALSO

git-lfs-clean(1), git-lfs-push(1).

Part of the git-lfs(1) suite.
