= git-lfs-uninstall(1)

== NAME

git-lfs-uninstall - Remove Git LFS configuration

== SYNOPSIS

[source,console,subs="verbatim,quotes",role=synopsis]
----
*git lfs uninstall*
----

== DESCRIPTION

Perform the following actions to remove the Git LFS configuration:

* Remove the `lfs` clean and smudge filters from the global Git config.
* Uninstall the Git LFS pre-push hook if run from inside a Git
repository.

== OPTIONS

`-l`::
`--local`::
  Removes the `lfs` smudge and clean filters from the local repository's Git
  config, instead of the global Git config (`~/.gitconfig`).
`-w`::
`--worktree`::
  Removes the `lfs` smudge and clean filters from the current working tree's Git
  config, instead of the global Git config (`~/.gitconfig`) or local repository's
  Git config (`$GIT_DIR/config`). If multiple working trees are in use, the Git
  config extension `worktreeConfig` must be enabled to use this option. If only
  one working tree is in use, `--worktree` has the same effect as `--local`.
  This option is only available if the installed Git version is at least 2.20.0
  and therefore supports the `worktreeConfig` extension.
`--system`::
  Removes the `lfs` smudge and clean filters from the system Git config, instead
  of the global Git config (`~/.gitconfig`).
`--skip-repo`::
  Skips cleanup of the local repo; use if you want to uninstall the global LFS
  filters but not make changes to the current repo.

== SEE ALSO

git-lfs-install(1), git-worktree(1).

Part of the git-lfs(1) suite.
