name: CI
on: [push, pull_request]
env:
  GOTOOLCHAIN: local

jobs:
  build-docker:
    name: Build Linux packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - run: git fetch origin "+${GITHUB_REF}:${GITHUB_REF}"
      if: ${{ github.ref_type == 'tag' }}
    - uses: ruby/setup-ruby@v1
    - run: git clone https://github.com/chrisd8088/build-dockers.git "$HOME/build-dockers"
    - run: (cd "$HOME/build-dockers" && git checkout centos-7-mirror-update)
    - run: (cd "$HOME/build-dockers" && ./build_dockers.bsh)
    - run: ./docker/run_dockers.bsh --prune
