name: CI
on: [push, pull_request]
env:
  GOTOOLCHAIN: local

jobs:
  build-docker:
    name: Build Linux packages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ${{ github.ref }}
    - run: git clone https://github.com/git-lfs/build-dockers.git "$HOME/build-dockers"
    - run: (cd "$HOME/build-dockers" && ./build_dockers.bsh)
    - run: ./docker/run_dockers.bsh --prune
