name: CI
on: [push, pull_request]
env:
  GOTOOLCHAIN: local

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: false
        ref: ${{ github.ref }}
    - run: mkdir -p "$HOME/test1"
      shell: bash
    - uses: ruby/setup-ruby@v1
    - run: mkdir -p "$HOME/test2"
      shell: bash
    - run: gem install asciidoctor
    - run: Rename-Item -Path C:\msys64 -NewName msys64-tmp -Force
      # We move the MSYS2 installed for Ruby aside to prevent use of its Git,
      # which does not honour the PATH we set to our built git-lfs binary.
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23.x'
    - run: mkdir -p "$HOME/go/bin"
      shell: bash
    - run: set GOPATH=%HOME%\go
    - run: choco install -y InnoSetup
    - run: make man
      shell: bash
    - run: GOPATH="$HOME/go" PATH="$HOME/go/bin:$PATH" go install github.com/josephspurrier/goversioninfo/cmd/goversioninfo@latest
      shell: bash
    - uses: git-for-windows/setup-git-for-windows-sdk@v1
      with:
        flavor: minimal
      # We install the SDK so as to have access to the msgfmt.exe binary
      # from the GNU gettext package.
    - run: set -x; env; type bash; cygpath -aw /; cat /etc/profile
      shell: bash
    - run: GOPATH="$HOME/go" PATH="$HOME/go/bin:$PATH" env -u TMPDIR script/cibuild
      shell: bash
      # We clear the TMPDIR set for Ruby so mktemp and Go use the same
      # volume for temporary files.
